"""Generate GitHub Pages HTML files from briefing Markdown."""

from __future__ import annotations

import html
import logging
from pathlib import Path

import markdown

logger = logging.getLogger(__name__)


def generate_site(
    *,
    detailed_markdown: str,
    date_slug: str,
    docs_dir: str = "docs",
) -> tuple[Path, Path, Path]:
    docs_path = Path(docs_dir)
    docs_path.mkdir(parents=True, exist_ok=True)

    article_html = _markdown_to_html(detailed_markdown)
    title = _extract_title(detailed_markdown, default=f"AIニュース詳細版 {date_slug}")
    full_html = _wrap_html(title=title, body=article_html)

    dated_path = docs_path / f"{date_slug}.html"
    latest_path = docs_path / "latest.html"
    index_path = docs_path / "index.html"

    dated_path.write_text(full_html, encoding="utf-8")
    latest_path.write_text(full_html, encoding="utf-8")

    if not index_path.exists():
        index_path.write_text(_index_html(), encoding="utf-8")

    logger.info("GitHub Pages用HTMLを生成しました。file=%s", dated_path)
    logger.info("latest.htmlを更新しました。file=%s", latest_path)
    return dated_path, latest_path, index_path


def _markdown_to_html(markdown_text: str) -> str:
    return markdown.markdown(
        markdown_text,
        extensions=["extra", "sane_lists", "nl2br"],
        output_format="html5",
    )


def _extract_title(markdown_text: str, *, default: str) -> str:
    for line in markdown_text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return default


def _wrap_html(*, title: str, body: str) -> str:
    safe_title = html.escape(title)
    return f"""<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f7f8fa;
      --paper: #ffffff;
      --text: #18202a;
      --muted: #5f6b7a;
      --line: #d8dee7;
      --accent: #0b6bcb;
    }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.75;
    }}
    main {{
      max-width: 860px;
      margin: 0 auto;
      padding: 24px 16px 56px;
    }}
    article {{
      background: var(--paper);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: clamp(18px, 4vw, 40px);
    }}
    h1, h2, h3 {{
      line-height: 1.35;
      letter-spacing: 0;
    }}
    h1 {{
      font-size: clamp(1.7rem, 4vw, 2.4rem);
      margin: 0 0 1.2rem;
    }}
    h2 {{
      border-top: 1px solid var(--line);
      margin-top: 2rem;
      padding-top: 1.4rem;
      font-size: 1.35rem;
    }}
    h3 {{
      font-size: 1.08rem;
      margin-top: 1.4rem;
    }}
    a {{
      color: var(--accent);
      overflow-wrap: anywhere;
    }}
    li {{
      margin: 0.35rem 0;
    }}
    code {{
      background: #eef2f7;
      border-radius: 4px;
      padding: 0.1rem 0.3rem;
    }}
    blockquote {{
      margin: 1rem 0;
      padding-left: 1rem;
      color: var(--muted);
      border-left: 4px solid var(--line);
    }}
    .footer {{
      margin-top: 24px;
      color: var(--muted);
      font-size: 0.9rem;
      text-align: center;
    }}
  </style>
</head>
<body>
  <main>
    <article>
{body}
    </article>
    <p class="footer">Generated by GitHub Actions</p>
  </main>
</body>
</html>
"""


def _index_html() -> str:
    body = """
<h1>AIニュース詳細版</h1>
<p>最新号は <a href="./latest.html">latest.html</a> から読めます。</p>
"""
    return _wrap_html(title="AIニュース詳細版", body=body)

